[manifest]
version = "1.0.0"
priority = -2

[vars]

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = 'replace_card.states.visible = false'
position = 'before'
payload = '''
SMODS.change_base(replace_card, "Clubs", nil)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
G.SPLASH_LOGO = Sprite(0, 0, 
        13*SC_scale, 
        13*SC_scale*(G.ASSET_ATLAS["balatro"].py/G.ASSET_ATLAS["balatro"].px),
        G.ASSET_ATLAS["balatro"], {x=0,y=0})
'''
position = 'at'
payload = '''
G.SPLASH_LOGO = Sprite(0, 0,
		13*SC_scale,
		13*SC_scale*(G.ASSET_ATLAS["paca_splash"].py/G.ASSET_ATLAS["paca_splash"].px),
		G.ASSET_ATLAS["paca_splash"], {x=0,y=0})
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = 'if not initial then G.GAME.blind:debuff_card(self) end'
position = 'before'
payload = '''
initial = true
'''
match_indent = true

# Wow Funny
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "SC = Card(G.ROOM.T.w/2 - SC_scale*G.CARD_W/2, 10. + G.ROOM.T.h/2 - SC_scale*G.CARD_H/2, SC_scale*G.CARD_W, SC_scale*G.CARD_H, G.P_CARDS.empty, G.P_CENTERS['j_joker'])"
position = "at"
payload = '''

if math.fmod(os.time(), 2) == 0 then
	SC = Card(G.ROOM.T.w/2 - SC_scale*G.CARD_W/2, 10. + G.ROOM.T.h/2 - SC_scale*G.CARD_H/2, SC_scale*G.CARD_W, SC_scale*G.CARD_H, G.P_CARDS.empty, G.P_CENTERS['j_paca_nerdy_title'])
else
	SC = Card(G.ROOM.T.w/2 - SC_scale*G.CARD_W/2, 10. + G.ROOM.T.h/2 - SC_scale*G.CARD_H/2, SC_scale*G.CARD_W, SC_scale*G.CARD_H, G.P_CARDS.empty, G.P_CENTERS['j_paca_nerdy_title'])
end
'''
match_indent = true